### ISSUE TITLE
 Linux clients freeze irregularly

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1071]
Author: tiffie (tiffie)
Date: 2018-02-14
Redmine Issue: 1071, https://dev.etlegacy.com/issues/1071

---

Basically it sounds like this one:
https://dev.etlegacy.com/issues/401

After a short while on this server:
37.187.79.49:27964

etl uses 100% cpu and freezes.
Nothing helps but killing it

```<code class="bash">etl +connect 37.187.79.49:27964
ET Legacy v2.75-1537-gf8842e6d linux-i386 Feb 13 2018 DEBUG
Zone megs: 64
Info: fs_game now defaults to 'legacy' mod instead of 'etmain'
----- FS_Startup -----
Current search path:
    /home/user/.etlegacy/legacy
    /home/user/.etlegacy/legacy/pak3_v2.75_dirty.pk3 (1072 files)
    /home/user/.etlegacy/legacy/pak3_v2.75.pk3 (951 files)
    /home/user/.etlegacy/legacy/etl_bin_v2.75_dirty.pk3 (6 files)
    /home/user/.etlegacy/legacy/etl_bin_v2.75.pk3 (8 files)
    /home/user/.etlegacy/legacy/etl_bin_v2.75.a21a9b69.pk3 (8 files)
    /usr/lib/etlegacy/legacy
    /usr/lib/etlegacy/legacy/pak3_v2.75_dirty.pk3 (1073 files)
    /usr/lib/etlegacy/legacy/etl_bin_v2.75_dirty.pk3 (2 files)
    /home/user/.etlegacy/etmain
    /home/user/.etlegacy/etmain/venice.pk3 (330 files)
    /home/user/.etlegacy/etmain/sw_oasis_b3.pk3 (45 files)
    /home/user/.etlegacy/etmain/sw_goldrush_te.pk3 (48 files)
    /home/user/.etlegacy/etmain/supply.pk3 (44 files)
    /home/user/.etlegacy/etmain/italyfp2.pk3 (325 files)
    /home/user/.etlegacy/etmain/dubrovnik_final.pk3 (186 files)
    /home/user/.etlegacy/etmain/caen2.pk3 (85 files)
    /home/user/.etlegacy/etmain/bremen_final.pk3 (100 files)
    /usr/lib/etlegacy/etmain
    /usr/lib/etlegacy/etmain/pak2.pk3 (22 files)
    /usr/lib/etlegacy/etmain/pak1.pk3 (10 files)
    /usr/lib/etlegacy/etmain/pak0.pk3 (3725 files)

----------------------
8040 files in pk3 files
^2*** '/home/user/.etlegacy/legacy/profiles/ETUser/profile.pid' ***
Creating PID file 'profiles/ETUser/profile.pid'
execing default.cfg
execing profiles/ETUser/etconfig.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
Not logging server attacks to disk.
----- Client Initialization -----
----- Initializing Renderer ----
*** 'librenderer_opengl1_i386.so' ***
Trying to load "librenderer_opengl1_i386.so" from "."...
Trying to load "librenderer_opengl1_i386.so" from "/usr/lib/etlegacy"...
-------------------------------
ETKEY found.
Available client translations: Czech German Greek English Esperanto Spanish Finnish French Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian
Available mod translations: Czech German Greek English Esperanto Spanish Finnish French Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian
Language set to English
----- Client Initialization Complete -----
----- R_Init -----
SDL build version 2.0.7 - link version 2.0.7.
SDL initialized driver "x11"
Initializing OpenGL display
Estimated display aspect: 1.778
...setting mode -2: 1920x1080
Using 24 color bits, 24 depth, 0 stencil display.
Available modes [13]: '1280x720 1600x900 1920x1080 1280x800 1440x900 1680x1050 720x480 640x480 800x600 1024x768 1152x864 720x576 1280x1024'
Using GLEW 2.1.0
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 550 Ti/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 390.25
Using vanilla renderer
Initializing OpenGL extensions
...found OpenGL extension - GL_EXT_texture_compression_s3tc
...found OpenGL extension - GL_EXT_texture_env_add
...found OpenGL extension - GL_ARB_multitexture
GL_MAX_TEXTURE_SIZE: 16384
GL_MAX_ACTIVE_TEXTURES_ARB: 4
PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
MODE: -2, SCREEN: 1920 x 1080 fullscreen (ratio 1.7778) Hz:N/A
GAMMA: hardware w/ 0 overbright bits
rendering primitives: single glDrawElements
texturemode: GL_LINEAR_MIPMAP_LINEAR
picmip: 0
texture bits: 32
multitexture: enabled
compiled vertex arrays: enabled
texenv add: enabled
compressed textures: enabled
Initializing Shaders
----- finished R_Init -----
------ Initializing Sound (1)------
SDL_Init( SDL_INIT_AUDIO )... OK
SDL audio driver is "pulseaudio".
SDL_AudioSpec:
  Format:   AUDIO_S16LSB
  Freq:     44100
  Samples:  1024
  Channels: 2
  Silence:  0
  Size:     4096
Starting SDL audio callback...
SDL audio initialized.
----- Sound Info -----
sound system is muted
    1 stereo
32768 samples
   16 samplebits
    1 submission_chunk
44100 speed
0x5a64d7e0 dma buffer
No background file.
----------------------
Sound initialization successfully done
s_backend set to SDL2
--------------------------------
Sound memory manager started
Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/user/.etlegacy, legacy, ui.mp.i386.so)
Sys_LoadDll(/usr/lib/etlegacy/legacy/ui.mp.i386.so)... succeeded
Sys_LoadDll(legacy/ui) found vmMain function at 0xb0767c30
Initializing Legacy ui v2.75-970-g655726d
147 UI cvars in use.
Total favourite servers restored: 3
SQLite3 libversion 3.21.0 - database URL 'etl.db' - in file
... loading existing database '/home/user/.etlegacy/etl.db'
... database file '/home/user/.etlegacy/etl.db' loaded
SQLite3 ET: L [1] database '/home/user/.etlegacy/etl.db' init in [0] ms - autocommit 1
--- Common Initialization Complete ---
IP: 127.0.0.1
IP: 192.168.178.30
Opening IP socket: 0.0.0.0:27960
Network initialized.
*** '/home/user/.etlegacy/legacy/profiles/ETUser/etconfig.cfg' ***
MOTD: resolving motd.etlegacy.com... resolved to 5.135.27.11:27951
37.187.79.49:27964 resolved to 37.187.79.49:27964
Connected to a pure server.
----- FS_Startup -----
Current search path:
    /home/user/.etlegacy/legacy/pak3_v2.75.pk3 (951 files)
        on the pure list
    /home/user/.etlegacy/legacy/etl_bin_v2.75.pk3 (8 files)
        on the pure list
    /home/user/.etlegacy/etmain/venice.pk3 (330 files)
        on the pure list
    /home/user/.etlegacy/etmain/sw_oasis_b3.pk3 (45 files)
        on the pure list
    /home/user/.etlegacy/etmain/sw_goldrush_te.pk3 (48 files)
        on the pure list
    /home/user/.etlegacy/etmain/supply.pk3 (44 files)
        on the pure list
    /usr/lib/etlegacy/etmain/pak2.pk3 (22 files)
        on the pure list
    /usr/lib/etlegacy/etmain/pak1.pk3 (10 files)
        on the pure list
    /usr/lib/etlegacy/etmain/pak0.pk3 (3725 files)
        on the pure list
    /home/user/.etlegacy/etmain/italyfp2.pk3 (325 files)
        on the pure list
    /home/user/.etlegacy/etmain/dubrovnik_final.pk3 (186 files)
        on the pure list
    /home/user/.etlegacy/etmain/caen2.pk3 (85 files)
        on the pure list
    /home/user/.etlegacy/etmain/bremen_final.pk3 (100 files)
        on the pure list
    /home/user/.etlegacy/legacy
    /home/user/.etlegacy/legacy/pak3_v2.75_dirty.pk3 (1072 files)
        not on the pure list
    /home/user/.etlegacy/legacy/etl_bin_v2.75_dirty.pk3 (6 files)
        not on the pure list
    /home/user/.etlegacy/legacy/etl_bin_v2.75.a21a9b69.pk3 (8 files)
        not on the pure list
    /usr/lib/etlegacy/legacy
    /usr/lib/etlegacy/legacy/pak3_v2.75_dirty.pk3 (1073 files)
        not on the pure list
    /usr/lib/etlegacy/legacy/etl_bin_v2.75_dirty.pk3 (2 files)
        not on the pure list
    /home/user/.etlegacy/etmain
    /usr/lib/etlegacy/etmain
    
----------------------
8040 files in pk3 files
Client download complete
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
----- R_Init -----
GL_MAX_TEXTURE_SIZE: 16384
GL_MAX_ACTIVE_TEXTURES_ARB: 4
PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
MODE: -2, SCREEN: 1920 x 1080 fullscreen (ratio 1.7778) Hz:N/A
GAMMA: hardware w/ 0 overbright bits
rendering primitives: single glDrawElements
texturemode: GL_LINEAR_MIPMAP_LINEAR
picmip: 0
texture bits: 32
multitexture: enabled
compiled vertex arrays: enabled
texenv add: enabled
compressed textures: enabled
Initializing Shaders
----- finished R_Init -----
Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/user/.etlegacy, legacy, ui.mp.i386.so)
Sys_LoadDll(/usr/lib/etlegacy/legacy/ui.mp.i386.so)... succeeded
Sys_LoadDll(legacy/ui) found vmMain function at 0xb07682d0
Initializing Legacy ui v2.75
145 UI cvars in use.
Total favourite servers restored: 3
Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/user/.etlegacy, legacy, cgame.mp.i386.so)
Sys_LoadDll(/usr/lib/etlegacy/legacy/cgame.mp.i386.so)... failed: "Failed loading /usr/lib/etlegacy/legacy/cgame.mp.i386.so: /usr/lib/etlegacy/legacy/cgame.mp.i386.so: cannot open shared object file: No such file or directory"
Sys_LoadDll(/home/user/.etlegacy/legacy/cgame.mp.i386.so)... succeeded
Sys_LoadDll(legacy/cgame) found vmMain function at 0xaa98f8f0
Initializing Legacy cgame v2.75
170 client cvars in use.
Not logging client output to disk.
g_gametype will be changed upon restarting.
LOADING...  - collision map -
LOADING...  - sounds -
Initializing Sound Scripts
...loading 'sound/scripts/vo_allies.sounds'
...'sound/scripts/vo_allies.sounds' parsed - total script sounds: 48
...loading 'sound/scripts/vo_axis.sounds'
...'sound/scripts/vo_axis.sounds' parsed - total script sounds: 96
...loading 'sound/scripts/caen2.sounds'
...'sound/scripts/caen2.sounds' parsed - total script sounds: 118
...3 of 3 sound scripts files loaded. Total sounds: 118
done.
LOADING...  - graphics -
LOADING...  - maps/caen2.bsp -
stitched 0 LoD cracks
...loaded 12591 faces, 122 meshes, 251 trisurfs, 0 flares, 0 foliages
LOADING...  - entities -
LOADING...  - game media -
LOADING...  - textures -
LOADING...  - models -
LOADING...  - heads-up display -
...properties for hud 3 have been read.
...hud count: 4
LOADING...  - weapons -
LOADING...  - items -
LOADING...  - inline models -
LOADING...  - server models -
LOADING...  - particles -
LOADING...  - classes -
LOADING...  - game media -
LOADING...  - flamechunks -
LOADING...  - clients -
LoadLocations: location data for map caen2 loaded
145 locations loaded.
CL_InitCGame:  2.98 seconds
Com_TouchMemory: 0 msec -342520457 
*** '/home/user/.etlegacy/legacy/hunkusage.dat' ***
*** '/home/user/.etlegacy/legacy/profiles/ETUser/etconfig.cfg' ***
wolfadmin: This server is running WolfAdmin, type /wolfadmin for more information.</code>
```

After that only chat output is sent to stdout/stderr

Then after killing:
 ```<code class="bash">----- CL_Shutdown -----
----- FS_Startup -----
Current search path:
    /home/user/.etlegacy/legacy
    /home/user/.etlegacy/legacy/pak3_v2.75_dirty.pk3 (1072 files)
    /home/user/.etlegacy/legacy/pak3_v2.75.pk3 (951 files)
    /home/user/.etlegacy/legacy/etl_bin_v2.75_dirty.pk3 (6 files)
    /home/user/.etlegacy/legacy/etl_bin_v2.75.pk3 (8 files)
    /home/user/.etlegacy/legacy/etl_bin_v2.75.a21a9b69.pk3 (8 files)
    /usr/lib/etlegacy/legacy
    /usr/lib/etlegacy/legacy/pak3_v2.75_dirty.pk3 (1073 files)
    /usr/lib/etlegacy/legacy/etl_bin_v2.75_dirty.pk3 (2 files)
    /home/user/.etlegacy/etmain
    /home/user/.etlegacy/etmain/venice.pk3 (330 files)
    /home/user/.etlegacy/etmain/sw_oasis_b3.pk3 (45 files)
    /home/user/.etlegacy/etmain/sw_goldrush_te.pk3 (48 files)
    /home/user/.etlegacy/etmain/supply.pk3 (44 files)
    /home/user/.etlegacy/etmain/italyfp2.pk3 (325 files)
    /home/user/.etlegacy/etmain/dubrovnik_final.pk3 (186 files)
    /home/user/.etlegacy/etmain/caen2.pk3 (85 files)
    /home/user/.etlegacy/etmain/bremen_final.pk3 (100 files)
    /usr/lib/etlegacy/etmain
    /usr/lib/etlegacy/etmain/pak2.pk3 (22 files)
    /usr/lib/etlegacy/etmain/pak1.pk3 (10 files)
    /usr/lib/etlegacy/etmain/pak0.pk3 (3725 files)
    
----------------------
8040 files in pk3 files
Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/user/.etlegacy, legacy, ui.mp.i386.so)
Sys_LoadDll(/usr/lib/etlegacy/legacy/ui.mp.i386.so)... succeeded
Sys_LoadDll(legacy/ui) found vmMain function at 0xb0767c30
Initializing Legacy ui v2.75-970-g655726d
147 UI cvars in use.
Total favourite servers restored: 3
Closing SDL audio device...
SDL audio device shut down.
RE_Shutdown( 1 )
SDL input devices shut down.
-----------------------
PID file removed.
Network shutdown.</code>
```

```<code class="bash">etl -v
Client: ET Legacy v2.75-1537-gf8842e6d linux-i386 Feb 13 2018 DEBUG
Masked as: ET 2.60b linux-i386 May  8 2006
Built: 2018-02-13T20:25:15 UTC
</code>
```
```<code class="bash">pacman -Q enemy-territory-data 
enemy-territory-data 2.60b-14</code>
```

Is there any way to get more detailed debugging output?
How can I provide more information?

---

Related issue(s): #953

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-02-14T19:56:28Z

---

I think this is a duplicate - see #953 

Which Linux is used?

**Comment by ETLegacyTeam** [comment]
From: tiffie (tiffie)
Date: 2018-02-14T20:46:50Z

---

IR4T4 wrote:
> I think this is a duplicate - see #953 
> 
That could be, but I use the 32 bit version
I don't know what mod "cgame" exactly is. 

> Which Linux is used?

Arch Linux
I used the AUR Packages "etlegacy32-git" and "etlegacy32-mod-git"
etlegacy32-git 2.75.1537.gf8842e6d-1
etlegacy32-mod-git 2.75.1537.gf8842e6d-1

Any chance to provide more help? It's definitely reproducible on that server for me - I can't even play one map without the problem occuring. Maybe I should mention that this haven't happened on other servers.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-02-15T11:05:17Z

---

Why there is a ui binary in fs_basepath see -> /usr/lib/etlegacy/legacy/ui.mp.i386.so ?

```
Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/user/.etlegacy, legacy, ui.mp.i386.so)
Sys_LoadDll(/usr/lib/etlegacy/legacy/ui.mp.i386.so)... succeeded
Sys_LoadDll(legacy/ui) found vmMain function at 0xb07682d0
Initializing Legacy ui v2.75
145 UI cvars in use.
Total favourite servers restored: 3
Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/user/.etlegacy, legacy, cgame.mp.i386.so)
Sys_LoadDll(/usr/lib/etlegacy/legacy/cgame.mp.i386.so)... failed: "Failed loading /usr/lib/etlegacy/legacy/cgame.mp.i386.so: /usr/lib/etlegacy/legacy/cgame.mp.i386.so: cannot open shared object file: No such file or directory" 
Sys_LoadDll(/home/user/.etlegacy/legacy/cgame.mp.i386.so)... succeeded
Sys_LoadDll(legacy/cgame) found vmMain function at 0xaa98f8f0

```

UI is loaded from fs_basepath, CGAME from fs_homepath. Both should be loaded from fs_homepath

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-02-15T11:16:33Z

---

If this is the install method of the AUR package the maintainer should fix that.

There are no extracted ui and cgame binary in fs_basepath.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2018-02-15T13:25:02Z

---

I checked the AUR packages and they are fine. I'm not sure why ui.so is loaded from basepath (I can't reproduce). Did you add that file there manually?

Also, I do note you have a mixture of Legacy files present (2.75 downloaded from server, but v2.75-970-g655726d ui on a  v2.75-1537-gf8842e6d install). Check your homepath in ~/.etlegacy/legacy and remove obsolete files.
Once this is cleared out, we can focus on the freeze issue.

**Comment by ETLegacyTeam** [comment]
From: tiffie (tiffie)
Date: 2018-02-16T20:18:11Z

---

Spyhawk wrote:
> I checked the AUR packages and they are fine. I'm not sure why ui.so is loaded from basepath (I can't reproduce). Did you add that file there manually?
> 
Yes, I ln'ed them (it seemed liked an error), but they are not the reason (I just removed them)

> Also, I do note you have a mixture of Legacy files present (2.75 downloaded from server, but v2.75-970-g655726d ui on a  v2.75-1537-gf8842e6d install). Check your homepath in ~/.etlegacy/legacy and remove obsolete files.
I removed the whole folder, connected again and had the same problem (though it seemed to happen after a longer period of time than before the removal - but that may be coincidental)
> Once this is cleared out, we can focus on the freeze issue.

Lets do that

**Comment by ETLegacyTeam** [comment]
From: tiffie (tiffie)
Date: 2018-02-16T20:32:03Z

---

definitely coincidental...

**Comment by ETLegacyTeam** [comment]
From: tiffie (tiffie)
Date: 2018-02-18T09:51:59Z

---

Maybe it matters:
```<code>pacman -Qs opengl
local/freeglut 3.0.0-2
    Provides functionality for small OpenGL programs
local/glew 2.1.0-1
    The OpenGL Extension Wrangler Library
local/glu 9.0.0-4
    Mesa OpenGL Utility library
local/gtkglext 1.2.0-10
    opengl extensions for gtk2
local/lib32-glu 9.0.0-3
    Mesa OpenGL utility library (32 bits)
local/lib32-mesa 17.3.3-1
    an open-source implementation of the OpenGL specification (32-bit)
local/lib32-nvidia-utils 390.25-1
    NVIDIA drivers utilities (32-bit)
local/libepoxy 1.4.3-1
    Library handling OpenGL function pointer management
local/mesa 17.3.3-2
    an open-source implementation of the OpenGL specification
local/nvidia-utils 390.25-2
    NVIDIA drivers utilities</code>
```

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-02-21T14:51:24Z

---

tiffie, please start the game with gdb. I would like to know if the freeze on your system is caused in cgame. gdb won't show detailed info because of 'missing' build parameter but it should at least show us the affected game module.

https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide

Steps:

- gdb ./etl

- enter 'run' 

--> on freeze press STRG+C in in gdb terminal

- enter 'backtrace'

**Comment by ETLegacyTeam** [comment]
From: tiffie (tiffie)
Date: 2018-02-25T11:59:03Z

---

@
...
[skipnotify]ETLPlayer: Good game!
tty]
Thread 1 "etl" received signal SIGINT, Interrupt.
0xa9b01792 in ?? () from /home/user/.etlegacy/legacy/cgame.mp.i386.so
(gdb) backtrace
#0  0xa9b01792 in ?? () from /home/user/.etlegacy/legacy/cgame.mp.i386.so
#1  0xa9af794d in ?? () from /home/user/.etlegacy/legacy/cgame.mp.i386.so
#2  0xa9afb367 in ?? () from /home/user/.etlegacy/legacy/cgame.mp.i386.so
#3  0xa9ae743a in ?? () from /home/user/.etlegacy/legacy/cgame.mp.i386.so
#4  0xa9aff590 in ?? () from /home/user/.etlegacy/legacy/cgame.mp.i386.so
#5  0xa9aa5a38 in vmMain () from /home/user/.etlegacy/legacy/cgame.mp.i386.so
#6  0x56590711 in VM_CallFunc (vm=0x574617f0 <vmTable+208>, callNum=3) at /tmp/yaourt-tmp-user/aur-etlegacy32-git/src/etlegacy/src/qcommon/vm.c:758
#7  0x565a9f9b in CL_CGameRendering () at /tmp/yaourt-tmp-user/aur-etlegacy32-git/src/etlegacy/src/client/cl_cgame.c:1223
#8  0x565c2396 in SCR_DrawScreenField () at /tmp/yaourt-tmp-user/aur-etlegacy32-git/src/etlegacy/src/client/cl_scrn.c:399
#9  0x565c24a7 in SCR_UpdateScreen () at /tmp/yaourt-tmp-user/aur-etlegacy32-git/src/etlegacy/src/client/cl_scrn.c:443
#10 0x565b85c1 in CL_Frame (msec=<optimized out>) at /tmp/yaourt-tmp-user/aur-etlegacy32-git/src/etlegacy/src/client/cl_main.c:2195
#11 0x565717b4 in Com_Frame () at /tmp/yaourt-tmp-user/aur-etlegacy32-git/src/etlegacy/src/qcommon/common.c:3438
#12 0x565d9b2b in Sys_GameLoop () at /tmp/yaourt-tmp-user/aur-etlegacy32-git/src/etlegacy/src/sys/sys_main.c:994
#13 0x56560eda in main (argc=3, argv=0xffffcf84) at /tmp/yaourt-tmp-user/aur-etlegacy32-git/src/etlegacy/src/sys/sys_main.c:1102
@

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-02-25T13:46:37Z

---

Thank you. It's a duplicate -  #953.
