### ISSUE TITLE
Game Crashes/Freeze during loading favorite servers when FEATURE_IPV6 enabled.

### ISSUE THREAD

**Issue by pemensik** [etlegacy/etlegacy#1520]
Current master, commit 886f0ef0d6a48b527a25409dbd6eb350e6610e48, seems to have broken initialization.

As soon as I add one server to favorites and quit, I can no longer start ./etl, until I delete ~/.etlegacy/etl.db.

It crashes on null net_enabled, when checking favorite. This seems to be done before NET_Init could initialize cvars.

```
#0  0x08070666 in Sys_StringToSockaddr (s=s@entry=0xffffb9f0 "78.47.238.205", sadr=sadr@entry=0xffffb950, sadr_len=sadr_len@entry=128, family=0)
    at /home/pemensik/upstream/etlegacy/src/qcommon/net_ip.c:347
#1  0x080708c1 in Sys_StringToAdr (s=0xffffb9f0 "78.47.238.205", a=0xffffbe10, family=NA_UNSPEC) at /home/pemensik/upstream/etlegacy/src/qcommon/net_ip.c:488
#2  0x08070467 in NET_StringToAdr (s=0x0, a=0xffffbe10, family=NA_UNSPEC) at /home/pemensik/upstream/etlegacy/src/qcommon/net_chan.c:786
#3  0x08088d64 in DB_callbackFavorites (NotUsed=0x0, argc=7, azColName=0xa4349c8, argv=0xa4349e4) at /home/pemensik/upstream/etlegacy/src/client/cl_db.c:203
#4  DB_callbackFavorites (NotUsed=0x0, argc=7, argv=0xa4349e4, azColName=0xa4349c8) at /home/pemensik/upstream/etlegacy/src/client/cl_db.c:192
#5  0xf7cc9f10 in sqlite3_exec () from /lib/libsqlite3.so.0
#6  0x08089145 in DB_LoadFavorites (profile=0xf6a70304 "pemensik") at /home/pemensik/upstream/etlegacy/src/client/cl_db.c:240
#7  0x0809bb61 in LAN_LoadCachedServers () at /home/pemensik/upstream/etlegacy/src/client/cl_ui.c:83
#8  0x0809c074 in CL_UISystemCalls (args=0xffffc050) at /home/pemensik/upstream/etlegacy/src/client/cl_ui.c:1234
#9  0x0807b6f0 in VM_DllSyscall (arg=<optimized out>) at /home/pemensik/upstream/etlegacy/src/qcommon/vm.c:358
#10 0xc9fbca6f in trap_LAN_LoadCachedServers () from /home/pemensik/.etlegacy/legacy/ui.mp.i386.so
#11 0x00000058 in ?? ()
#12 0x00000000 in ?? ()
(gdb) frame
#0  0x08070666 in Sys_StringToSockaddr (s=s@entry=0xffffb9f0 "78.47.238.205", sadr=sadr@entry=0xffffb950, sadr_len=sadr_len@entry=128, family=0)
    at /home/pemensik/upstream/etlegacy/src/qcommon/net_ip.c:347
347				if (net_enabled->integer & NET_PRIOV6)
(gdb) p net_enabled
$1 = (cvar_t *) 0x0
```

**Comment by rafal1137** [comment]
Just a note from me:

> vid_restart command needs to be inspected

After calling this command issue seems resolved.
