### ISSUE TITLE
check if etmain/pak0/1/2.pk3 exists

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#343]
Author: kkthx (kkthx)
Date: 2013-09-09
Redmine Issue: 343, https://dev.etlegacy.com/issues/343

---

While running etl.exe without etmain directory(with pk3s inside) the game is trying to execute and orange screen appers.
(how to reproduce: compile into build dir and execute w/o setting the base/home paths)
Issue occurs while compiling newest commits from repo. The downloaded version(2.71rc1) is free from this bug(like original version)
Compiled using Visual Studio 2012

---

Related commit(s):
624e831ded11ee58970cb0e58d8649e0e94f6e08 - client: temporary workaround for base data files c..
 1de5212f963cd6c588cba9d680efb42e1d044206 - generic: improved pak0.pk3 missing error message, ..
 996fadb1fc909604f6c677b47849a75a8a7e6795 - generic: improved pak0.pk3 missing error message, ..
 df058612971de2ad69ab769ef88ddd25d11515de - misc: use CvarVariableString function to get pid_f..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2013-09-09T22:05:15Z

---

Wouldn't be a hard requirement make the compilation of binary on exotic platform or build server possibly more annoying?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-09-10T05:10:01Z

---

I think a check for the assets pk3s is a nice to have (sv_pure 1 only) but the above use case won't happen very often for end users: Our installers are already checking for missing genuine paks and are offering the option to install them.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-09-17T11:54:04Z

---

Just to clear things up. This issue occurs, because the following check in @FS_InitFilesystem@ is no longer valid since we distribute @default.cfg@ in etl_bin.pk3:

```<code class="C">
if (FS_ReadFile("default.cfg", NULL) <= 0)
{
	Com_Error(ERR_FATAL, "FS_InitFilesystem: Couldn't load default.cfg - I am missing essential files!\nVerify your installation and make sure genuine ET files\n- pak0.pk3\n- pak1.pk3\n- pak2.pk3\nare located in 'etmain' folder of fs_basepath: %s", fs_basepath->string);
}</code>
```

I will add a better check and allow users to automatically download and unpack default data files from Harlekin's installer through our update server (at least on unix-like systems, on Windows we would have to download data files directly and that would be illegal)

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-09-17T12:59:45Z

---

I just noticed there is another obsolete check for @default.cfg@ in @FS_Restart@.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-02-10T09:29:29Z

---

With the recent "changes":http://dev.etlegacy.com/projects/etlegacy/repository/revisions/6f05f8f6e0d75d3aa397787003b016230fea2647, et:l segfaults on Linux if the pak.pk3 files aren't present instead of displaying the usual error message.

```
(gdb) bt
#0  0x08075e43 in Com_Shutdown (badProfile=qfalse) at /home/curtis/src/git/etlegacy/src/qcommon/common.c:3445
#1  0x08071b72 in Com_Error (code=0, 
    fmt=0x8198220 "FS_InitFilesystem: Original game data files not found.\n\nPlease copy pak0.pk3, pak1.pk3 and pak2.pk3 from the 'etmain' path of your Wolfenstein: Enemy Territory installation to:\n\n\"%s%c%s\"\n\n") at /home/curtis/src/git/etlegacy/src/qcommon/common.c:391
#2  0x0808ec3a in FS_CheckRequiredFiles (checksumFeed=0) at /home/curtis/src/git/etlegacy/src/qcommon/files.c:4417
#3  0x0808ed09 in FS_InitFilesystem () at /home/curtis/src/git/etlegacy/src/qcommon/files.c:4455
#4  0x08074e8e in Com_Init (commandLine=0xffffcbe0 "") at /home/curtis/src/git/etlegacy/src/qcommon/common.c:2767
#5  0x080e5895 in main (argc=1, argv=0xffffd0a4) at /home/curtis/src/git/etlegacy/src/sys/sys_main.c:1091

```

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-02-10T14:07:14Z

---

Segfault is fixed.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-02-17T10:22:44Z

---

This issue has actually been fixed a long time ago... Closing now.
