### ISSUE TITLE
Receiving SIGIOT on MacOSX

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#385]
Author: otty (otty)
Date: 2013-11-01
Redmine Issue: 385, https://dev.etlegacy.com/issues/385

---

The system: MacOSX 10.9 Mavericks, 2.9 Ghz Intel Core i5 IMac, 8Gbyte RAM with NVIDIA GeForce GTX 660M 512MB

After a few tweaks, etlegacy compiles fine on my mac. The game starts up fine( NOTE: to get the render2 compiled i needed to fix a bug in a GLSL shader, and disable a non-sense error message in OpenGL Context retrieving, i'll post a new bug report for that later). When starting a map, the system crashes after eg. "LOADING... maps/oasis.bsp". I traced down to CL_Shutdown recieving SIGIOT (Signal 6 for malfunctinal memory access). I'm fairly new to my IMac and the C/C++ world, so i have no idea how to debug this error.

Can anyone replicate this behaviour?

This error occurs with render1/render2, SDL1, SDL2 and all possible build configurations(Note: as i can say, only linking for architecture x86_64 works, because i have no 32bit libs in my Mac)

I've attached a log of the game starting with

./etl +set developer 1 +set com_hunkmegs 512 +devmap oasis

Regards,
Adrian

---

Related issue(s): #74

---

Related commit(s):
2e5362318dbcac8052f089a444e8b6f9e2a89c2c - general: workaround for OS X 10.9 crash in strncpy..
 6165c89fa8e954090ab1fd4a41570a6a68aa9576 - generic: strncpy with in == out causes signal 6 if..

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-11-01T12:47:53Z

---

I can confirm. Ioquake3 has the same issue on OS X Mavericks

Here is (unhelpful) gdb output: http://pastebin.com/qGm4WvMM

**Comment by ETLegacyTeam** [comment]
From: otty (otty)
Date: 2013-11-01T12:59:09Z

---

Radegast wrote:
> I can confirm. Ioquake3 has the same issue on OS X Mavericks
> 
> Here is (unhelpful) gdb output: http://pastebin.com/qGm4WvMM

Yes. I just checked ioquake3 and XreaL, same issue here. Tried to compile with gcc-4.9: same thing.

**Comment by ETLegacyTeam** [comment]
From: otty (otty)
Date: 2013-11-01T13:13:34Z

---

Radegast wrote:
> I can confirm. Ioquake3 has the same issue on OS X Mavericks

Fix found for ETL:

before performing strncpy we need to check if dest equals src in Q_strncpyz (q_shared.c) :

    if (src == dest) {
        return;
    }

If you look into your (very helpfull!) gdb output, you see this:

> #8  0x00042734 in Q_strncpyz (dest=0x240caf8 "goldrush.bsp", src=0x240caf8 "goldrush.bsp", destsize=9) 
> #9  0x00042633 in COM_StripExtension (in=0x240caf8 "goldrush.bsp", out=0x240caf8 "goldrush.bsp", destsize=64) 

We can not strncpy a block to itself, can't we? 

EDIT: i checked again, copying from src to dest while src is dest happens much more often.
EDIT2: this fixes the bug in ioquake3 as well.

EDIT3: Ensiform suggest to fix COM_StripExtension, it causes the issue in Q_strncpyz.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-11-05T16:21:57Z

---

I've committed your fix until there is a real fix in @COM_StripExtension@.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-11-07T10:47:12Z

---

Zturtleman fixed @Com_StripExtension@: https://github.com/ioquake/ioq3/commit/fd4cd6612d2c3be0ff604d64cc96d72eba2c4427

**Comment by ETLegacyTeam** [comment]
From: Anonymous (Anonymous)
Date: 2013-11-07T11:15:34Z

---

Applied in changeset commit:6165c89fa8e954090ab1fd4a41570a6a68aa9576.
