### ISSUE TITLE
You will not loose disguise by shooting if the enemy looks through binoculars

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#679]
Author: @saukko28 (Saukko)
Date: 2014-11-29
Redmine Issue: 679, https://dev.etlegacy.com/issues/679

---

As the title says. I can reproduce this 100% of the time, I can't lose my disguise if I shoot with a weapon straight to the enemy who is looking me with binoculars right in front of me. And when he doesn't look through the binoculars, I will lose my disguise straight away as intended.

-*S

---

Related commit(s):
3766a92d7e58d4f37d34fcc8bd8f167ee74ba8de - game: binoculars check head of players instead of ..
 3350cd645635da252a74d830dfcaf7a5db116746 - game: do not change origin of landmines, refs 679
 d106e968bcfabb0a5065db2cffa86018a949a2a6 - game: fixed dereference before null checks, refs ..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-11-24T13:45:36Z

---

Just had a closer look:
* This actually works correctly, but only if the whole enemy box is visible through binoculars. When the disguised enemy is too close and partially visible, he will not lose his disguise.
* The issue seems to be located in the G_CullPointAndRadius check in G_VisibleFromBinoculars() and G_VisibleFromBinoculars_Box(), where a qfalse is triggered when the disguised enemy shoot at close range. Might be something wrong with the origin value.

Note: ETPub doesn't have G_VisibleFromBinoculars_Box(), only G_VisibleFromBinoculars(). This has been introduced in https://github.com/etlegacy/etlegacy/commit/88bdabc693ffb6959469c04a18297c56dabccda2 (cleanup commit, looks ok to me).

Edit: it seems this work when looking at the feet of the disguised coverops. I guess the origin point is, in that case, correctly seen through binoculars.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-11-25T06:15:59Z

---

Applied in changeset 3766a92d7e58d4f37d34fcc8bd8f167ee74ba8de.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-11-26T08:40:34Z

---

Reopening. This change causes a crash when spotting landmines.

```Program received signal SIGSEGV, Segmentation fault.
0x00007fff83bfceb1 in G_VisibleFromBinoculars (viewer=0x7fff86a97a40 <g_entities+13504>, ent=0x7fff86b0d178 <g_entities+494584>,
    origin=0x7fff86b0d2e0 <g_entities+494944>) at /home/user/dev/etlegacy/src/game/g_teammapdata.c:350
350             origin[2] += ent->client->ps.viewheight;
(gdb) backtrace
#0  0x00007fff83bfceb1 in G_VisibleFromBinoculars (viewer=0x7fff86a97a40 <g_entities+13504>, ent=0x7fff86b0d178 <g_entities+494584>,
    origin=0x7fff86b0d2e0 <g_entities+494944>) at /home/user/dev/etlegacy/src/game/g_teammapdata.c:350
#1  0x00007fff83bfeada in G_CheckSpottedLandMines () at /home/user/dev/etlegacy/src/game/g_teammapdata.c:1077
#2  0x00007fff83bfedc1 in G_UpdateTeamMapData () at /home/user/dev/etlegacy/src/game/g_teammapdata.c:1144
#3  0x00007fff83bb1514 in G_RunFrame (levelTime=388050) at /home/user/dev/etlegacy/src/game/g_main.c:4770
#4  0x00007fff83ba744f in vmMain (command=8, arg0=388050, arg1=4294965959, arg2=1024, arg3=4506202, arg4=0, arg5=47249005504, arg6=140737488347216)
    at /home/user/dev/etlegacy/src/game/g_main.c:695
#5  0x000000000044cc52 in VM_CallFunc (vm=0x14ba260 <vmTable>, callnum=8) at /home/user/dev/etlegacy/src/qcommon/vm.c:690
#6  0x000000000047d06d in SV_Frame (msec=11) at /home/user/dev/etlegacy/src/server/sv_main.c:1601
#7  0x0000000000438771 in Com_Frame () at /home/user/dev/etlegacy/src/qcommon/common.c:3325
#8  0x00000000004b730f in Sys_GameLoop () at /home/user/dev/etlegacy/src/sys/sys_main.c:965
#9  0x00000000004b7405 in main (argc=1, argv=0x7fffffffe058) at /home/user/dev/etlegacy/src/sys/sys_main.c:1043
(gdb) exit

```
