### ISSUE TITLE
Move translations to a GMS platform (e.g. Transifex)

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#763]
Author: Anonymous (Anonymous)
Date: 2015-01-09
Redmine Issue: 763, https://dev.etlegacy.com/issues/763

---

Forcing volunteers to study mostly Linux-only tools (e.g. Poedit) and open Pull Requests for every edit of translation is just not cool. Also updating .po files after every single template change is *pain*.

A platform like Transifex or Launchpad will help us crowdsource translations from concerned citizens without technical skills. Maintaining existing ones will become easier too.

**Comment by ETLegacyTeam** [comment]
From: Anonymous (Anonymous)
Date: 2015-01-10T12:18:44Z

---

Project and POT import are up and running at
https://www.transifex.com/projects/p/etlegacy

To do: export of translations to git repo.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2015-01-10T21:43:05Z

---

I followed the "tutorial on how to integrate Transifex with a Github repo":http://blog.transifex.com/post/67760039192/github-transifex-integration, but I do not think it is working.

When txgh receives a notification from Github, it shows this in the terminal:

```
178.17.4.25 - - [10/Jan/2015 21:43:37] "POST /hooks/github HTTP/1.1" 500 4850 0.0100
TypeError - no implicit conversion of nil into String:
        /usr/lib64/ruby/gems/2.0.0/gems/json-1.8.0/lib/json/common.rb:155:in `initialize'
        /usr/lib64/ruby/gems/2.0.0/gems/json-1.8.0/lib/json/common.rb:155:in `new'
        /usr/lib64/ruby/gems/2.0.0/gems/json-1.8.0/lib/json/common.rb:155:in `parse'
        /home/etlegacy/webapps/txgh/app/app.rb:61:in `block in <class:Hooks>'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1541:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1541:in `block in compile!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `[]'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (3 levels) in route!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:966:in `route_eval'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (2 levels) in route!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:987:in `block in process_route'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `catch'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `process_route'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:948:in `block in route!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `each'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `route!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1059:in `block in dispatch!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1056:in `dispatch!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `block in call!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `call!'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:870:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/xss_header.rb:18:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/showexceptions.rb:21:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:175:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1949:in `call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/puma-2.5.1/lib/puma/rack_patch.rb:13:in `call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
        /usr/local/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/puma-2.5.1/lib/puma/server.rb:472:in `handle_request'
        /home/etlegacy/.gem/ruby/2.0.0/gems/puma-2.5.1/lib/puma/server.rb:343:in `process_client'
        /home/etlegacy/.gem/ruby/2.0.0/gems/puma-2.5.1/lib/puma/server.rb:242:in `block in run'
        /home/etlegacy/.gem/ruby/2.0.0/gems/puma-2.5.1/lib/puma/thread_pool.rb:92:in `call'
        /home/etlegacy/.gem/ruby/2.0.0/gems/puma-2.5.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'

```
