### ISSUE TITLE
ET:L compiled with Clang or gcc-llvm crashes

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#84]
Author: @JanSimek (Radegast)
Date: 2012-10-07
Redmine Issue: 84, https://dev.etlegacy.com/issues/84

---

```
Sys_LoadDll(/tmp/ui_mac): succeeded ...
Sys_LoadDll(ui) found vmMain function at 0x1b90ca5c

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000041
0x0001ce85 in CopyString (in=0x41 <Address 0x41 out of bounds>) at /Users/jansimek/Development/etlegacy/src/qcommon/common.c:1337
1337		if (!in[0])

```

Full backtrace is attached to this bug report.

To prevent users who don't know about this bug from compiling ET:L, clang build is disabled. To enable it, comment out this code in source:src/qcommon/q_platform.h:

```<code class="C">
// FIXME: add llvm/clang support                                                                                                                                                                          
#ifdef __llvm__
#error Although ET:L can be compiled with gcc-llvm/clang, it will crash upon start up!
#endif // __llvm__ 
</code>
```

---

Related issue(s): #74

---

Related commit(s):
784cc7fad19d67b7bdaf83834f12b18605ddcb1b - general: clang/gcc-llvm build fixed by IR4T4 and /..

**Comment by ETLegacyTeam** [comment]
From: @morsik (morsik)
Date: 2012-10-07T16:41:08Z

---

*Confirmed* on Linux with clang version 3.1 (branches/release_31).

This is probably something about dynamic load vm...

```
mmap2(0x4fcc5000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 126, 0x5e) = 0x4fcc5000
mmap2(0x4fccb000, 3315872, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x4fccb000
close(126)                              = 0
write(2, "Sys_LoadDll(/home/morsik/.etwolf"..., 69Sys_LoadDll(/home/morsik/.etwolf/etmain/ui.mp.i386.so): succeeded ...) = 69
write(2, "\33[0m\n", 5
)                 = 5
write(2, "Sys_LoadDll(ui) found vmMain fun"..., 51Sys_LoadDll(ui) found vmMain function at 0x4fc8a086) = 51
write(2, "\33[0m\n", 5
)                 = 5
--- {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x41} (Segmentation fault) ---

```

**Comment by ETLegacyTeam** [comment]
From: @morsik (morsik)
Date: 2012-10-07T16:55:43Z

---

gdb output:

```
Sys_LoadDll(/home/morsik/.etwolf/etmain/ui.mp.i386.so)... 
Sys_LoadDll(/home/morsik/.etwolf/etmain/ui.mp.i386.so): succeeded ...
Sys_LoadDll(ui) found vmMain function at 0x504e0086

Program received signal SIGSEGV, Segmentation fault.
0x0805b29f in CopyString (in=0x41 <Address 0x41 out of bounds>) at /home/morsik/Projects/etlegacy/src/qcommon/common.c:1337
1337		if (!in[0])
(gdb) bt
#0  0x0805b29f in CopyString (in=0x41 <Address 0x41 out of bounds>) at /home/morsik/Projects/etlegacy/src/qcommon/common.c:1337
#1  0x0808da64 in Cvar_Get (var_name=0x50505c55 <trap_Cvar_Register+61> "\203\304([\303", <incomplete sequence \350>, 
    var_value=0x41 <Address 0x41 out of bounds>, flags=1350284384) at /home/morsik/Projects/etlegacy/src/qcommon/cvar.c:376
#2  0x0808f368 in Cvar_Register (vmCvar=0x5050e261, varName=0x50505c55 <trap_Cvar_Register+61> "\203\304([\303", <incomplete sequence \350>, 
    defaultValue=0x41 <Address 0x41 out of bounds>, flags=1350284384) at /home/morsik/Projects/etlegacy/src/qcommon/cvar.c:1178
#3  0x080bab3c in CL_UISystemCalls (args=0xffffcf14) at /home/morsik/Projects/etlegacy/src/client/cl_ui.c:908
#4  0x080902be in VM_DllSyscall (arg=65) at /home/morsik/Projects/etlegacy/src/qcommon/vm.c:343
#5  0x50505c55 in trap_Cvar_Register () from /home/morsik/.etwolf/etmain/ui.mp.i386.so
#6  0x504de7f7 in _UI_Init () from /home/morsik/.etwolf/etmain/ui.mp.i386.so
#7  0x504e01f6 in vmMain () from /home/morsik/.etwolf/etmain/ui.mp.i386.so
#8  0x08090c5f in VM_Call (vm=0xa55eca8 <vmTable>, callnum=1) at /home/morsik/Projects/etlegacy/src/qcommon/vm.c:714
#9  0x080be14a in CL_InitUI () at /home/morsik/Projects/etlegacy/src/client/cl_ui.c:1352
#10 0x080c99ce in CL_StartHunkUsers () at /home/morsik/Projects/etlegacy/src/client/cl_main.c:3270
#11 0x0805ea89 in Com_Init (commandLine=0xffffd24c "") at /home/morsik/Projects/etlegacy/src/qcommon/common.c:3112
#12 0x080e483b in main (argc=1, argv=0xffffd704) at /home/morsik/Projects/etlegacy/src/sys/sys_main.c:715

```

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2012-10-09T13:57:13Z

---

Applied in changeset commit:784cc7fad19d67b7bdaf83834f12b18605ddcb1b.
