### ISSUE TITLE
Fix linux client freeze

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#852]
Author: @IR4T4 (IR4T4)
Date: 2015-08-02
Redmine Issue: 852, https://dev.etlegacy.com/issues/852

---

...

---

Related commit(s):
936e932350c24bda4444f9eddf4b59513624166a - cgame: no pic for ent type ME_DESTRUCT_2 in CG_Dra..
 21522fcce587933f96eed08560495979cf6fd3cb - cgame: no pic for ent type ME_DESTRUCT_2 in CG_Dra..
 85085ffa7ab4bd3c6c3a791d6b78f0506da99b4c - cgame: build fix

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-08-08T14:06:44Z

---

Can't reproduce anymore.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-08-09T20:58:56Z

---

The crash could be reproduced on gaming session.

Backtrace for reference:
```
Program received signal SIGSEGV, Segmentation fault.
0xd213ba4a in CG_DrawMapEntity (mEnt=0xd227a108 <mapEntities+264>, x=648.5, y=16.5, w=99, h=99, mEntFilter=0, scissor=0xffffca68, interactive=qfalse, snap=0xd4154354 <cg+52>, icon_size=5)
    at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_commandmap.c:833
833     /media/sf_legacy/lnxetlegacy32/src/cgame/cg_commandmap.c: Datei oder Verzeichnis nicht gefunden.
(gdb) BACKTRACE
#0  0xd213ba4a in CG_DrawMapEntity (mEnt=0xd227a108 <mapEntities+264>, x=648.5, y=16.5, w=99, h=99, mEntFilter=0, scissor=0xffffca68, interactive=qfalse, snap=0xd4154354 <cg+52>, icon_size=5)
    at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_commandmap.c:833
#1  0xd213c822 in CG_DrawMap (x=648.5, y=16.5, w=99, h=99, mEntFilter=0, scissor=0xffffca68, interactive=qfalse, alpha=1, borderblend=qfalse) at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_commandmap.c:1187
#2  0xd213d7dd in CG_DrawAutoMap (x=648.5, y=16.5, w=99, h=99) at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_commandmap.c:1480
#3  0xd215b3c4 in CG_DrawNewCompass (location=...) at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_draw_hud.c:1598
#4  0xd215fdd0 in CG_DrawGlobalHud () at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_draw_hud.c:2629
#5  0xd2154415 in CG_Draw2D () at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_draw.c:3352
#6  0xd215516e in CG_DrawActive (stereoView=STEREO_CENTER) at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_draw.c:3585
#7  0xd21c699d in CG_DrawActiveFrame (serverTime=1340503, stereoView=STEREO_CENTER, demoPlayback=qfalse) at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_view.c:2151
#8  0xd218c5c3 in vmMain (command=3, arg0=1340503, arg1=0, arg2=0, arg3=0, arg4=0, arg5=0, arg6=0, arg7=0, arg8=0, arg9=0, arg10=0, arg11=0) at /media/sf_legacy/lnxetlegacy32/src/cgame/cg_main.c:64
#9  0x080a74c9 in VM_CallFunc (vm=0x9bb4bf0 <vmTable+208>, callnum=3) at /media/sf_legacy/lnxetlegacy32/src/qcommon/vm.c:690
#10 0x080c9fae in CL_CGameRendering (stereo=STEREO_CENTER) at /media/sf_legacy/lnxetlegacy32/src/client/cl_cgame.c:1238
#11 0x080e11db in SCR_DrawScreenField (stereoFrame=STEREO_CENTER) at /media/sf_legacy/lnxetlegacy32/src/client/cl_scrn.c:385
#12 0x080e12be in SCR_UpdateScreen () at /media/sf_legacy/lnxetlegacy32/src/client/cl_scrn.c:439
#13 0x080daa2c in CL_Frame (msec=10) at /media/sf_legacy/lnxetlegacy32/src/client/cl_main.c:2254
#14 0x0808a806 in Com_Frame () at /media/sf_legacy/lnxetlegacy32/src/qcommon/common.c:3365
#15 0x080f43dc in Sys_GameLoop () at /media/sf_legacy/lnxetlegacy32/src/sys/sys_main.c:965
#16 0x080f44cb in main (argc=1, argv=0xffffd364) at /media/sf_legacy/lnxetlegacy32/src/sys/sys_main.c:1043
(gdb) QUIT

```

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-08-16T05:21:31Z

---

Can't reproduce anymore.
