### ISSUE TITLE
Alt-Tab crash

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#986]
Author: @rmarquis (Spyhawk)
Date: 2017-02-01
Redmine Issue: 986, https://dev.etlegacy.com/issues/986

---

Alt-Tab sometimes crashed the game.

How to reproduce: Open console, then press Alt-Tab.
The crashlog contains this info: "Q_strncpyz: NULL src".

Many "unknown cmd minimize" are printed in console when using Alt-Tab, but this seems unrelated to the crash - would still be great to fix it.
This _might_ be platform dependent issue, tested on Linux.

```
Connected to a pure server.
[skipnotify]^1FIGHT!
[skipnotify]unknown cmd minimize
[skipnotify]unknown cmd minimize
[skipnotify]unknown cmd minimize
[skipnotify]^7(^o[BOT]^7Vokur^7)^3(^3^1Oasis Water Pump^3): ^5I'm constructing!
[skipnotify]unknown cmd minimize
[skipnotify]unknown cmd minimize
^7^o[BOT]^7Milius^7^7 failed to spot ^7^o[BOT]^7Sean^7^7's Landmine
^7^o[BOT]^7Stinger^7^7 failed to spot ^7^o[BOT]^7Sean^7^7's Landmine
^7^o[BOT]^7Ryver^7^7 failed to spot ^7^o[BOT]^7Sean^7^7's Landmine
[skipnotify]unknown cmd minimize
^7^o[BOT]^7Halfbaked^7^7 was killed by ^7^o[BOT]^7Kaolin^7^7's Thompson
^7^o[BOT]^7Mungri^7^7 was killed by ^7^o[BOT]^7Blackadder^7^7's MP 40
[skipnotify]unknown cmd minimize
^7^o[BOT]^7CraigChrist^7^7 failed to spot ^7^o[BOT]^7Bean^7^7's Landmine
^7^o[BOT]^7Kaolin^7^7 failed to spot ^7^o[BOT]^7Bean^7^7's Landmine
[skipnotify]unknown cmd minimize
[skipnotify]unknown cmd minimize
^7^o[BOT]^7Mungri^7^7 vaporized himself
^7^o[BOT]^7Sean^7^7 was killed by ^7^o[BOT]^7Ryver^7^7's Thompson
^7^o[BOT]^7Ryver^7^7 was killed by ^7^o[BOT]^7Brad^7^7's FG 42
^7^o[BOT]^7Vokur^7^7 was killed by ^7^o[BOT]^7Blackadder^7^7's MP 40
[skipnotify]^7(^o[BOT]^7Ryver^7)^3(^3^3Old City^3): ^5Hold your fire!
^7^o[BOT]^7Milius^7^7 was killed by ^7^o[BOT]^7Nohope^7^7's MP 40
^7^1:^7L^1|^7Spyhaw^1k^7^7 was killed by ^7^o[BOT]^7Bean^7^7's K43
^7^o[BOT]^7Bean^7^7 was killed by ^7^o[BOT]^7Stinger^7^7's FG 42
^7^o[BOT]^7CraigChrist^7^7 was shelled by ^7^o[BOT]^7Nohope^7^7's artillery support
^7^o[BOT]^7Stinger^7^7 failed to spot ^7^o[BOT]^7Bean^7^7's Landmine
[skipnotify]unknown cmd minimize
----- CL_Shutdown -----
Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/remy/.etlegacy, legacy, ui.mp.i386.so)
Sys_LoadDll(./legacy/ui.mp.i386.so)... failed: "Failed loading ./legacy/ui.mp.i386.so: ./legacy/ui.mp.i386.so: cannot open shared object file: No such file or directory"
Sys_LoadDll(/home/remy/.etlegacy/legacy/ui.mp.i386.so)... succeeded
Sys_LoadDll(legacy/ui) found vmMain function at 0x6aa78900
Initializing Legacy ui v2.75-451-g60a2323f
145 UI cvars in use.
Total favourite servers restored: 2
Closing SDL audio device...
SDL audio device shut down.
RE_Shutdown( 1 )
SDL input devices shut down.
-----------------------
----- Server Shutdown -----
==== ShutdownGame (0 - oasis) ====
^2<EndGame>
^2-- Script System Info --
^2Current Memory Usage 3.61193 MB
^2Soft Memory Usage 4.81677 MB
^2Hard Memory Limit 5.35197 MB
^2System Memory Usage 2.21348 MB
^2Full Collects 2
^2Inc Collects 1
^2GC Warnings 0
^2Threads: 1, 0 Running, 0 Blocked, 1 Sleeping
^2ShutdownOmniBot
---------------------------
PID file removed.
SQLite3 can't close database - not active.
Q_strncpyz: NULL src
```

---

Related commit(s):
b99bd97234743a538f538ba564eb29dde6f7aab0 - qcommon: fixed Alt-Tab crash when console is open ..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-02-01T17:08:43Z

---

```
qcommon/q_shared.c:1459:void Q_strncpyz(char *dest, const char *src, size_t destsize)
qcommon/q_shared.c:1467:                Com_Error(ERR_FATAL, "Q_strncpyz: NULL src");
qcommon/q_shared.c:1635:        Q_strncpyz(dest + l1, src, size - l1);
qcommon/q_shared.h:703:void Q_strncpyz(char *dest, const char *src, size_t destsize);
```
Line 1467 is a global error, not really helping here.
 
With a breakpoint and backtrace:

```
(gdb) bt
#0  Q_strncpyz (dest=0x81e0498 <completionString> "", src=0x0, destsize=1024) at /home/remy/dev/etlegacy/src/qcommon/q_shared.c:1467
#1  0x0808c3d3 in Field_CompleteCommand (cmd=0x9128740 <g_consoleField+12> "", doCommands=qtrue, doCvars=qtrue) at /home/remy/dev/etlegacy/src/qcommon/common.c:3762
#2  0x0808ca7c in Field_AutoComplete (field=0x9128734 <g_consoleField>) at /home/remy/dev/etlegacy/src/qcommon/common.c:4018
#3  0x0808c868 in Console_AutoComplete (field=0x9128734 <g_consoleField>, completionOffset=0x91234a0 <con+655432>) at /home/remy/dev/etlegacy/src/qcommon/common.c:3951
#4  0x080e0917 in Console_Key (key=9) at /home/remy/dev/etlegacy/src/client/cl_keys.c:651
#5  0x080e22d6 in CL_KeyEvent (key=9, down=qtrue, time=22336) at /home/remy/dev/etlegacy/src/client/cl_keys.c:1456
#6  0x0808a20e in Com_EventLoop () at /home/remy/dev/etlegacy/src/qcommon/common.c:2503
#7  0x0808ba52 in Com_Frame () at /home/remy/dev/etlegacy/src/qcommon/common.c:3353
#8  0x081136a0 in Sys_GameLoop () at /home/remy/dev/etlegacy/src/sys/sys_main.c:967
#9  0x081137e0 in main (argc=1, argv=0xffffd164) at /home/remy/dev/etlegacy/src/sys/sys_main.c:1074
```

Commit of interest: https://github.com/etlegacy/etlegacy/commit/5b84ac0bd361dce5837c2fd591a298d97f511cc3

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-02-01T19:45:55Z

---

Applied in changeset commit:b99bd97234743a538f538ba564eb29dde6f7aab0.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-02-01T19:46:33Z

---

This is a Linux specific bug.
